-- Inserir os devocionais iniciais
insert into devotionals (
  day,
  title,
  verse_text,
  verse_reference,
  verse_book,
  verse_chapter,
  verse_number,
  devotional_text,
  practical_text
) values
(1, 'Começando com Propósito',
  'Antes de formar você no ventre, eu o escolhi; antes de você nascer, eu o separei.',
  'Jeremias 1:5',
  'JR',
  '1',
  '5',
  'Deus criou você intencionalmente. Nada em sua vida é fruto do acaso. Antes mesmo de você nascer, Ele já havia planejado sua existência e dado a você dons e talentos únicos para cumprir um propósito.',
  'Reserve cinco minutos hoje para orar e perguntar a Deus: "Qual é o propósito que o Senhor tem para mim?"'
),
(2, 'O Poder da Gratidão',
  'Deem graças em todas as circunstâncias, pois esta é a vontade de Deus para vocês em Cristo Jesus.',
  '1 Tessalonicenses 5:18',
  '1TS',
  '5',
  '18',
  'A gratidão tem o poder de transformar nossa perspectiva sobre a vida. Mesmo nos momentos difíceis, podemos encontrar razões para agradecer.',
  'Faça uma lista de 5 coisas pelas quais você é grato hoje.'
),
(3, 'Força na Fraqueza',
  'Minha graça é suficiente para você, pois o meu poder se aperfeiçoa na fraqueza.',
  '2 Coríntios 12:9',
  '2CO',
  '12',
  '9',
  'Nossas fraquezas não são obstáculos para Deus, mas oportunidades para Ele demonstrar Seu poder.',
  'Identifique uma área de fraqueza em sua vida e ore pedindo a Deus que demonstre Seu poder através dela.'
),
(4, 'Paz em Meio à Tempestade',
  'Deixo-lhes a paz; a minha paz lhes dou. Não a dou como o mundo a dá.',
  'João 14:27',
  'JO',
  '14',
  '27',
  'A paz que Jesus oferece é diferente da paz do mundo. Ela não depende das circunstâncias externas.',
  'Dedique 10 minutos hoje para meditar neste versículo e pedir a Deus Sua paz sobrenatural.'
),
(5, 'Renovação Diária',
  'As misericórdias do Senhor são a causa de não sermos consumidos, porque as suas misericórdias não têm fim.',
  'Lamentações 3:22-23',
  'LM',
  '3',
  '22-23',
  'Cada manhã é uma nova oportunidade de experimentar a misericórdia de Deus.',
  'Ao acordar amanhã, agradeça a Deus por três novas misericórdias que você vê em sua vida.'
);